[package]
name = "presensi_kajian"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.2.1"
dotenv = "0.15.0"
env_logger = "0.10.0"
serde = "1.0.152"
serde_json = "1.0.91"
tera = "1.17.1"
